#!/usr/bin/env bash
# Script that dumps all databases and archives the dump to a tar.gz format
mysqldump --all-databases -u root -p "$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
